trigger:
  branches:
    include:
    - main
    - features/*


pool: default

stages:
- stage: stageone_Planning 
  displayName: Planning Stage
  jobs:
  - job:
    displayName: Init & Plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: init task
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envt/Dev'
        backendServiceArm: 'Vinod_Sub_Service_connection'
        backendAzureRmStorageAccountName: 'mzeestg21'
        backendAzureRmContainerName: 'terrafromtfstate'
        backendAzureRmKey: 'tfstatefile'
    - task: TerraformTask@5
      displayName: Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envt/Dev'
        environmentServiceNameAzureRM: 'Vinod_Sub_Service_connection'